default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= [5, *ENV.values_at("RAILS_MAX_THREADS", "SIDEKIQ_CONCURRENCY")].map(&:to_i).max %>

development:
  <<: *default
  database: odin_flight_booker_development

test:
  <<: *default
  database: odin_flight_booker_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
